# Generated by Django 5.2.4 on 2025-07-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Do_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='isCompleted',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
    ]
